---
- name: Windows Server Setup
  hosts: windows_servers
  gather_facts: no
  tasks:
    - name: Disable screen timeout
      win_shell: |
        reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Power\PowerSettings\7516b95f-f776-4464-8c53-06167f40cc99\8EC4B3A5-6868-48c2-BE75-4F3044BE88A7" /v Attributes /t REG_DWORD /d 2 /f
        powercfg -change -standby-timeout-ac 0

    - name: Update WinGet
      win_shell: winget upgrade

    - name: Install PowerShell 7
      win_chocolatey:
        name: powershell-core
        state: present

    - name: Install Microsoft 365 modules
      win_shell: Install-Module -Name "AzureADPreview", "ExchangeOnlineManagement", MSOnline, "Microsoft.Graph", "MicrosoftTeams", "SharePointPnPPowerShellOnline" -Force -AllowClobber -Scope AllUsers -SkipPublisherCheck

    - name: Install WinFetch, LSD, Starship
      win_chocolatey:
        name: "{{ item }}"
        state: present
      loop:
        - winfetch
        - lsd
        - starship

    - name: Customize desktop and settings
      win_shell: |
        # Add your customizations here
        Add-Content -Path $PROFILE.AllUsersCurrentHost -Value 'Set-Alias -Name ls -Value "lsd" -Option AllScope'
        Add-Content -Path $PROFILE.AllUsersCurrentHost -Value 'Set-Alias -Name win -Value "winfetch" -Option AllScope'
        Add-Content -Path $PROFILE.AllUsersCurrentHost -Value 'winfetch'
        set-executionpolicy -executionpolicy bypass -scope currentuser -force
        winfetch

    - name: Run PowerShell scripts as Administrator
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File "{{ playbook_dir }}/scripts/seu_script.ps1"
      become: yes
      become_method: runas
      no_log: true  # Não registrar a saída dos scripts por questões de segurança















